# Generated by Django 3.0.3 on 2020-02-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_applicant_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='last_date',
            field=models.DateTimeField(null=True),
        ),
    ]
